"""Shared decision interface for online rollout and offline replay.

The policy sees only the *revealed* tree and picks a batch C of at most W
eligible nodes. Online, children are generated by a (stochastic) discovery
agent; in replay, the next recorded child is returned deterministically.
"""
from __future__ import annotations

from typing import Callable, Protocol

from .tree import ROOT, DiscoveryTree


class Env(Protocol):
    workers: int
    observed: DiscoveryTree
    rounds: int
    requests: int

    def legal(self) -> list[int]: ...
    def step(self, batch: list[int]) -> list[int]: ...


class _Base:
    def __init__(self, workers: int) -> None:
        self.workers = workers
        self.rounds = 0
        self.requests = 0
        self.observed = DiscoveryTree()

    def legal(self) -> list[int]:
        return self.observed.eligible()

    def _check(self, batch: list[int]) -> None:
        if len(batch) > self.workers:
            raise ValueError(f"batch {len(batch)} exceeds W={self.workers}")
        legal = set(self.legal())
        for v in batch:
            if v not in legal:
                raise ValueError(f"node {v} is not eligible (not root/leaf)")
        non_root = [v for v in batch if v != ROOT]
        if len(non_root) != len(set(non_root)):
            raise ValueError("a non-root node may appear once per batch")


class OnlineEnv(_Base):
    """generate(parent_node_or_None, tree) -> (score, meta) stands in for the
    discovery agent + evaluator (resume parent's workspace, produce an attempt)."""

    def __init__(self, workers: int, generate: Callable[[DiscoveryTree, int], tuple[float, dict]]) -> None:
        super().__init__(workers)
        self.generate = generate

    def step(self, batch: list[int]) -> list[int]:
        self._check(batch)
        if not batch:
            return []
        self.rounds += 1
        # Children are generated against the pre-round tree (parallel workers).
        results = [(v, *self.generate(self.observed, v)) for v in batch]
        new = []
        for parent, score, meta in results:
            new.append(self.observed.add(parent, score, **meta).id)
            self.requests += 1
        return new


class ReplayEnv(_Base):
    """Replays a recorded tree: no agent or evaluator is ever executed."""

    def __init__(self, recorded: DiscoveryTree, workers: int) -> None:
        super().__init__(workers)
        self.recorded = recorded
        self._revealed = {ROOT}
        self._to_rec = {ROOT: ROOT}  # observed id -> recorded id

    def done(self) -> bool:
        return len(self._revealed) == len(self.recorded.nodes)

    def step(self, batch: list[int]) -> list[int]:
        self._check(batch)
        if not batch:
            return []
        self.rounds += 1
        new = []
        # Reveal against the pre-round state so duplicates of root open distinct branches.
        picks = []
        taken: set[int] = set()
        for v in batch:
            for c in self.recorded.children[self._to_rec[v]]:
                if c not in self._revealed and c not in taken:
                    picks.append((v, c))
                    taken.add(c)
                    break
        for v, c in picks:
            rn = self.recorded.nodes[c]
            node = self.observed.add(v, rn.score, **rn.meta)
            self._to_rec[node.id] = c
            self._revealed.add(c)
            self.requests += 1
            new.append(node.id)
        return new
